### ISSUE TITLE
Speeding it up

### ISSUE THREAD

**Issue by Xentrics** [byrddev/CGoL#1]
Really nice solution. Using boolean algebra for this problem is nice. However, if you want to speed it up by 1/5 without loosing readability, you might truncate 

twoLiveNeig =    (GoL & lives2[2:end-1,2:end-1]) 
threeLiveNeig =  (GoL & lives3[2:end-1,2:end-1])  
reproduce =     (~GoL & lives3[2:end-1,2:end-1])
GoL = twoLiveNeig | threeLiveNeig | reproduce

down to just
twoLiveNeig =    (GoL & lives2[2:end-1,2:end-1]) 
GoL = twoLiveNeig | lives3[2:end-1,2:end-1]

(**reproduce  |  threeLiveNeight  ==  lives3[...]**)
Only if it is of interest for you, of course :).

**Comment by byrddev** [comment]
yes, very nice. thanks for the feedback.

one of the main reasons for being verbose was to show the Game of Life
rules explicitly and show how easy Julia code is to read.

but always, code improvements are welcome!
